"""Fapix database configuration. Generated by: fapix startdb"""

TORTOISE_ORM = {
    "connections": {
        "default": "sqlite:///home/hashim/Templates/pydash /fapix/testproject/E-learning/testdb.sqlite3",
    },
    "apps": {
        "models": {
            "models": [
                "aerich.models",
                "apps.auth.models",
                "apps.assessments.models",
                "apps.communications.models",
                "apps.courses.models",
            ],
            "default_connection": "default",
        },
    },
}


async def connect_db() -> None:
    from tortoise import Tortoise

    await Tortoise.init(config=TORTOISE_ORM, _enable_global_fallback=True)


async def disconnect_db() -> None:
    from tortoise import Tortoise

    await Tortoise.close_connections()
